version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql-counter
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    logging:
      driver: json-file
    networks:
      - practica
  redis:
    image: "redis:alpine"
    networks:
      - practica
    logging:
      driver: json-file
  mysql:
    build: ./mysql-counter/
    environment:
      MYSQL_DATABASE: 'TESTDB'
      # So you don't have to use root, but you can if you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    logging:
      driver: json-file
    networks:
      practica:
        aliases:
          - mysql-counter

networks:
    practica:
        driver: bridge